- src/App.js
- src/components/HomeNav.js
- src/components/Modal.js
- src/components/Navigation.js
- src/sass/app.scss
- src/sass/index.scss
> Testing fixes worked

- public/index.html
- src/components/TopicCard.js
- [] Complete, tested, ready to review and merge
> Some finalized items, working to complete functionality.

- .gitignore
- src/App.js
- src/components/ActionButton.js
- src/reducers/topicsReducer.js
> Updated location of the Add Topic button and color to match design

- src/App.js
- src/actions/userAuthActions.js
- src/components/Register_Login.js
- src/reducers/userAuthReducer.js
- src/sass/StyledRegister_login.js
> fixed routing issue for login

- src/components/ActionButton.js
> Fixed the button... again

- src/components/ActionButton.js
- src/components/Dashboard.js
- src/components/TopicBucket.js
- src/sass/actionButton.scss
- src/sass/dashboard.scss
- src/sass/index.scss
- src/sass/topicBuckets.scss
> ActionButton cleaned of in-line.

- package-lock.json
- package.json
- src/components/TopicBucket.js
- src/components/TopicCard.js
Added simple edit card modal for UI User Testing.
> Jessica modal

- src/components/TopicBucket.js
> fixed merge conflicts

- src/components/TopicBucket.js
Fixes # Text doesn't auto populate when a user tries to edit a field
> Topic Editing now gives the user their current text during editing.

- cypress/integration/dnd/register-authorize-spec.js
- cypress/integration/dnd/userFlow-spec.js
- cypress/integration/login-spec.js
- src/components/Register_Login.js
- src/components/TopicBucket.js
- src/components/TopicCard.js
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
> updated testing indetifiers and made login test with high confidence

- src/components/Dashboard.js
- src/components/Date.js
- src/components/Modal.js
- src/components/Navigation.js
- src/components/SvgComponent.js
- src/components/TopicBucket.js
- src/sass/dashboard.scss
- src/sass/navigation.scss
- src/sass/topicBuckets.scss
> Topic card

- src/components/TopicCard.js
- [x ] New feature (non-breaking change which adds functionality)
> Edit post dropdown menu

- .github/workflows/ci.yml
- .gitignore
- cypress/plugins/index.js
- cypress/support/index.js
- package-lock.json
- package.json
Runs Cypress, collects code coverage and publishes to Code Climate
> Cypress coverage report

- .vscode/settings.json
- package-lock.json
- package.json
- src/actions/userAuthActions.js
- src/components/Dashboard.js
- src/components/Dashboard_Account.js
- src/components/Dashboard_Feed.js
- src/components/Navigation.js
- src/components/TopicCard.js
- src/components/Twitter_Tweets.js
- src/reducers/userAuthReducer.js
- src/sass/dashboard_feed.scss
- src/sass/index.scss
- src/sass/topicCard_schedule.scss
- src/utils/PrivateRoute.js
> Twitter feed

- .vscode/settings.json
- src/components/TopicCard.js
> fixed date stuff

- cypress/integration/login-spec.js
- src/components/ActionButton.js
- src/components/Navigation.js
- src/components/TopicCard.js
- src/sass/actionButton.scss
- src/sass/topicBuckets.scss
- src/sass/topicCard_schedule.scss
> updated styling for navigation, dashboard, and topic/modals

- package-lock.json
- src/actions/topicsActions.js
- src/components/TopicTitle.js
> Fixed delete topic error

- src/components/ActionButton.js
- src/components/TopicCard.js
- src/components/TopicNav.js
> fixed issues

- src/components/Dashboard.js
- src/components/Navigation.js
- src/components/TopicCard.js
> fixed some console.log stuff

- src/actions/topicsActions.js
> edited editcard

- src/actions/userAuthActions.js
- src/components/Dashboard_Tweets.js
> fixed que backwards

- src/actions/userAuthActions.js
- src/components/Login.js
- src/components/Registration.js
> input fixes

- amplify.yml
Removes test config to fix Amplify build failure during test phase
> Remove test config from amplify build settings

- src/components/auth/TwitterConnect.js
- src/components/auth/TwitterConnectCallback.js
> use axiosWithAuth

- src/components/Home.js
- src/components/dashboard/MediaManager.js
- src/reducers/index.js
- src/reducers/userReducer.js
- src/sass/topicBuckets.scss
Fix Oauth bug and redux issues
> Bug fix/oauth redux

- src/components/Home.js
- src/components/auth/LoginOkta.js
- src/reducers/index.js
> persist user to postgres from okta after login

- src/actions/userActions.js
> kanban working

- src/actions/listsActions.js
- src/actions/userActions.js
Update api routes for new schema
> update api routes for new schema

- src/components/analytics/PopularWords.js
- src/components/analytics/Stats.js
- src/components/pages/Analytics.js
- src/components/pages/__tests__/Analytics.js
Adding popular words component to analytics page
> popular words component

- package-lock.json
- package.json
- src/components/analytics/GetStarted.js
- src/components/analytics/Stats.js
- src/components/analytics/Success.js
- src/components/analytics/__tests__/PopularWords.js
- src/components/analytics/__tests__/Stats.js
- src/components/nav/__tests__/MenuList.js
- src/components/pages/__tests__/Analytics.js
- src/utils/test-utils.js
Adding more tests for popWords component and small changes per DS request
> Add tests for popWords component

- src/actions/popwordsActions.js
- src/actions/statsActions.js
> Update DS endpoints

- package-lock.json
- package.json
- src/App.js
> Google Analytics added

- package.json
- src/components/analytics/__tests__/PopularWords.js
- src/components/nav/__tests__/MenuList.js
- src/components/pages/Landing.js
- src/components/pages/__tests__/Home.js
- src/components/pages/__tests__/Landing.js
> Bug fix/failing tests

- .github/workflows/ci.yml
- src/App.js
- src/AppRouter.js
Move landing page route outside of Security component
> Move landing page route outside of Security component

- .codeclimate.yml
- package.json
- src/actions/__tests__/ListsActions.js
- src/components/analytics/Stats.js
- src/components/kanban/Kanban.js
- src/components/kanban/ListHeader.js
- src/utils/__mocks__/axiosWithAuth.js
Adds more tests for Redux actions
> Add more tests for Redux actions

- src/actions/twitterActions.js
> update redux post with response when post to twitter

- src/components/nav/NavMenu.js
- src/muiCustomTheme.js
> add overflowX hidden to drawer

- src/components/analytics/Success.js
small words issue on success component
> fixed small words issue
